# Generated by Django 3.1.1 on 2020-09-19 01:34

import cpf_field.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cpf',
            field=cpf_field.models.CPFField(default='xxx.xxx.xxx-xx', max_length=14, verbose_name='cpf'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 9, 18), verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default='(xx)xxxx-xxxx', max_length=14, verbose_name='Telefone'),
        ),
    ]
