# Generated by Django 3.1.1 on 2020-09-19 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200918_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 1, 36, 32, 38552, tzinfo=utc), verbose_name='Data de Nascimento'),
        ),
    ]
