# Generated by Django 3.1.1 on 2020-09-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200918_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
    ]
