# Generated by Django 3.1.1 on 2020-11-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Mensagem'), (2, 'Aluguel'), (3, 'Devolucao')], null=True),
        ),
    ]
