# Generated by Django 3.1.1 on 2020-11-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20201107_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Mensagem'), (2, 'Aluguel'), (3, 'Aceito'), (4, 'Devolucao')], null=True),
        ),
    ]
