# Generated by Django 3.1.1 on 2020-10-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='produto',
        ),
    ]
