# Generated by Django 3.1.1 on 2020-10-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_remove_chat_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='nomeSala',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
