# Generated by Django 3.1.1 on 2020-09-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nome', models.CharField(max_length=30)),
                ('usuario_email', models.CharField(max_length=30)),
                ('usuario_senha', models.CharField(max_length=30)),
                ('usuario_tipo', models.IntegerField()),
            ],
        ),
    ]
