# Generated by Django 3.1.1 on 2020-09-20 00:54

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='cpf',
            field=cpf_field.models.CPFField(default='xxx.xxx.xxx-xx', max_length=14, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='telefone',
            field=models.CharField(max_length=12),
        ),
    ]
