# Generated by Django 3.1.1 on 2020-12-01 16:13

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20201201_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_usuario',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='cpf'),
        ),
    ]
