# Generated by Django 3.1.1 on 2020-09-24 04:44

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200919_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dados_usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
