# Generated by Django 3.1.1 on 2020-11-17 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='')),
                ('descricao', models.TextField(verbose_name='')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='')),
                ('condicoesUso', models.TextField(verbose_name='')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='', verbose_name='')),
                ('alugado', models.BooleanField(default=False)),
                ('estado', models.CharField(default='Pernambuco', max_length=100)),
                ('cidade', models.CharField(default='Recife', max_length=100)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoria')),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Aguardando Locador'), (2, 'Proposta cancelada'), (3, 'Proposta aceita'), (4, 'Encerrado'), (5, 'avaliado')], null=True)),
                ('encerrado', models.BooleanField(default=False)),
                ('locador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicostatus_user_locador', to=settings.AUTH_USER_MODEL)),
                ('locatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicostatus_user_locatario', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Inicio Aluguel')),
                ('fim', models.DateField(verbose_name='Fim Aluguel')),
                ('confirmado', models.BooleanField()),
                ('locador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_locador', to=settings.AUTH_USER_MODEL)),
                ('locatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_locatario', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='StatusAceito',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.historicostatus',),
        ),
        migrations.CreateModel(
            name='StatusAguardando',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.historicostatus',),
        ),
        migrations.CreateModel(
            name='StatusCancelado',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.historicostatus',),
        ),
        migrations.CreateModel(
            name='StatusEncerrado',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.historicostatus',),
        ),
    ]
