# Generated by Django 3.1.1 on 2020-11-06 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alugar',
            name='confirmado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='alugar',
            name='locador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_locador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alugar',
            name='locatario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_locatario', to=settings.AUTH_USER_MODEL),
        ),
    ]
