# Generated by Django 3.1.1 on 2020-11-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alugado',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='alugar',
            name='produto',
        ),
        migrations.AddField(
            model_name='alugar',
            name='produto',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
