# Generated by Django 3.1.1 on 2020-11-07 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201107_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alugar',
            name='produto',
        ),
        migrations.AddField(
            model_name='alugar',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
