# Generated by Django 3.1.1 on 2020-09-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200914_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clients_photos', verbose_name='Imagem'),
        ),
    ]
