# Generated by Django 3.1.1 on 2020-11-02 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_denuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Inicio Aluguel')),
                ('fim', models.DateField(verbose_name='Fim Aluguel')),
                ('locador', models.CharField(max_length=50)),
                ('locatario', models.CharField(max_length=50)),
                ('confirmarcao', models.BinaryField(default=0)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
