# Generated by Django 3.1.1 on 2020-09-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='condicoesUso',
            field=models.TextField(verbose_name='Condições de uso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoria'),
        ),
    ]
