# Generated by Django 3.1.1 on 2020-11-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alugar',
            name='confirmarcao',
        ),
        migrations.AddField(
            model_name='alugar',
            name='confirmado',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
